### ISSUE TITLE
Board not available in other browser

### ISSUE THREAD

**Issue by madamadam** [jh3y/tyto#56]
After adding a new board in one browser (firefox for example), it's not possible to copy its URL (http://example.com/tyto/public/#board/39081cf8-aaed-9cdc-0061-ce37373d9136) and open it in another browser (safari or chrome for example). The URL does not exist, instead I reach the location http://141.22.194.205/tyto/public/# where I can add an new board; choosing the old board is not available. I installed tyto on two different servers, the issue occurs in every case.

**Comment by jh3y** [comment]
Hi @madamadam .

Yes. This is actually the expected behaviour. `tyto` is a purely frontend application. It uses localStorage to maintain its state. It doesn't include any style of back end implementation. Therefore, you wouldn't be able to switch between browsers without using the import/export functionality. There is some information about this in the `README`.

Hope that clears it up.

@jh3y
